require "globalevent"
require "structutil"
require "logutil"
require "frame.cppobjectbase"
require "timermgr"
require "baseutil"
require "gameplay.inputmgr"
require "util.math"
require "util.configutil"
require "util.varwatcher"
-- require "testtemplate"