#include "LuaFixLink.h"
extern void FixLinkFunc_CoreUObject_uclass_all();
extern void FixLinkFunc_InputCore_uclass_all();
extern void FixLinkFunc_AssetRegistry_uclass_all();
extern void FixLinkFunc_Engine_uclass_all();
extern void FixLinkFunc_UMG_uclass_all();
extern void FixLinkFunc_Foliage_uclass_all();
extern void FixLinkFunc_AIModule_uclass_all();
extern void FixLinkFunc_VarWatcher_uclass_all();
extern void FixLinkFunc_CatchMe_CatchMeAIController();
extern void FixLinkFunc_CatchMe_CatchMeGameInstance();
extern void FixLinkFunc_CatchMe_CMCharacterBase();
extern void FixLinkFunc_CatchMe_CMFogMgr();
extern void FixLinkFunc_CatchMe_CMFogMgr_Test();
extern void FixLinkFunc_CatchMe_CMGameModeBase();
extern void FixLinkFunc_CatchMe_CMPlayerControllerBase();
extern void FixLinkFunc_CatchMe_CMSpectatorPawn();
extern void FixLinkFunc_CatchMe_LuaAnimInstance();
extern void FixLinkFunc_CatchMe_TestCaseActor();
extern void FixLinkFunc_CatchMe_CatchMeCharacter();
extern void FixLinkFunc_CatchMe_CatchMeGameMode();
extern void FixLinkFunc_CatchMe_CatchMePlayerController();
extern void FixLinkFunc_LuaPluginRuntime_uclass_all();
extern void FixLinkFunc_CoreUObject_ustruct_all();
extern void FixLinkFunc_InputCore_ustruct_all();
extern void FixLinkFunc_AssetRegistry_ustruct_all();
extern void FixLinkFunc_Engine_ustruct_all();
extern void FixLinkFunc_UMG_ustruct_all();
extern void FixLinkFunc_Foliage_ustruct_all();
extern void FixLinkFunc_AIModule_ustruct_all();
extern void FixLinkFunc_CatchMe_CharacterInfo();
extern void FixLinkFunc_CatchMe_SkillInfo();
extern void FixLinkFunc_LuaPluginRuntime_ustruct_all();
extern void FixLinkFunc_uenum_all();
void LuaFixLink()
{
	FixLinkFunc_CoreUObject_uclass_all();
	FixLinkFunc_InputCore_uclass_all();
	FixLinkFunc_AssetRegistry_uclass_all();
	FixLinkFunc_Engine_uclass_all();
	FixLinkFunc_UMG_uclass_all();
	FixLinkFunc_Foliage_uclass_all();
	FixLinkFunc_AIModule_uclass_all();
	FixLinkFunc_VarWatcher_uclass_all();
	FixLinkFunc_CatchMe_CatchMeAIController();
	FixLinkFunc_CatchMe_CatchMeGameInstance();
	FixLinkFunc_CatchMe_CMCharacterBase();
	FixLinkFunc_CatchMe_CMFogMgr();
	FixLinkFunc_CatchMe_CMFogMgr_Test();
	FixLinkFunc_CatchMe_CMGameModeBase();
	FixLinkFunc_CatchMe_CMPlayerControllerBase();
	FixLinkFunc_CatchMe_CMSpectatorPawn();
	FixLinkFunc_CatchMe_LuaAnimInstance();
	FixLinkFunc_CatchMe_TestCaseActor();
	FixLinkFunc_CatchMe_CatchMeCharacter();
	FixLinkFunc_CatchMe_CatchMeGameMode();
	FixLinkFunc_CatchMe_CatchMePlayerController();
	FixLinkFunc_LuaPluginRuntime_uclass_all();
	FixLinkFunc_CoreUObject_ustruct_all();
	FixLinkFunc_InputCore_ustruct_all();
	FixLinkFunc_AssetRegistry_ustruct_all();
	FixLinkFunc_Engine_ustruct_all();
	FixLinkFunc_UMG_ustruct_all();
	FixLinkFunc_Foliage_ustruct_all();
	FixLinkFunc_AIModule_ustruct_all();
	FixLinkFunc_CatchMe_CharacterInfo();
	FixLinkFunc_CatchMe_SkillInfo();
	FixLinkFunc_LuaPluginRuntime_ustruct_all();
	FixLinkFunc_uenum_all();
}